# Generated by Django 4.1.1 on 2022-10-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ErrorBrowser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'verbose_name_plural': 'Errors'},
        ),
        migrations.AlterModelOptions(
            name='errorcategory',
            options={'verbose_name_plural': 'ErrorCategories'},
        ),
        migrations.AlterModelOptions(
            name='errortype',
            options={'verbose_name_plural': 'ErrorTypes'},
        ),
        migrations.AlterField(
            model_name='error',
            name='errorType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ErrorBrowser.errortype', verbose_name='typ błędu'),
        ),
        migrations.AlterField(
            model_name='errorcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nazwa kategorii'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='errorCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ErrorBrowser.errorcategory', verbose_name='kategoria'),
        ),
        # migrations.CreateModel(
        #     name='ErrorDefinition',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('namespace', models.CharField(max_length=255)),
        #         ('methodName', models.JSONField()),
        #         ('someList', models.ManyToManyField(to='ErrorBrowser.errorcategory')),
        #     ],
        # ),
    ]
