# Generated by Django 4.1.1 on 2022-10-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErrorBrowser', '0002_alter_error_options_alter_errorcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testField', models.CharField(max_length=255)),
            ],
        ),
        # migrations.DeleteModel(
        #     name='ErrorDefinition',
        # ),
    ]
