# Generated by Django 4.1.1 on 2022-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErrorBrowser', '0004_errordefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableName', models.CharField(max_length=50)),
                ('columnName', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=250)),
                ('isRegex', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='errordefinition',
            old_name='someList',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='errordefinition',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='errordefinition',
            name='filters',
            field=models.ManyToManyField(to='ErrorBrowser.columnfilter'),
        ),
    ]
