# Generated by Django 4.1.1 on 2022-10-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErrorBrowser', '0005_columnfilter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnName', models.CharField(choices=[('ID', 'ID'), ('DT', 'DT'), ('Source', 'Source'), ('HostName', 'HostName'), ('UserName', 'UserName'), ('SQLServerName', 'SQLServerName'), ('SQLDBName', 'SQLDBName'), ('SQLLogin', 'SQLLogin'), ('ExceptionMessage', 'ExceptionMessage'), ('ExceptionStackTrace', 'ExceptionStackTrace'), ('APIFunction', 'APIFunction'), ('APIError', 'APIError'), ('GIDTyp', 'GIDTyp'), ('GIDFirma', 'GIDFirma'), ('GIDNumer', 'GIDNumer'), ('GIDLp', 'GIDLp'), ('SubGIDLp', 'SubGIDLp'), ('Comment', 'Comment'), ('ExternalID', 'ExternalID'), ('ExternalID2', 'ExternalID2')], max_length=50)),
                ('value', models.CharField(max_length=250)),
                ('isRegex', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StackFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnName', models.CharField(choices=[('ID', 'ID'), ('ErrorId', 'ErrorId'), ('Lp', 'Lp'), ('Namespace', 'Namespace'), ('Class', 'Class'), ('MethodName', 'MethodName'), ('MethodFullSignature', 'MethodFullSignature'), ('LineNumber', 'LineNumber')], max_length=50)),
                ('value', models.CharField(max_length=250)),
                ('isRegex', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='ColumnFilter',
        ),
        migrations.AlterField(
            model_name='errordefinition',
            name='filters',
            field=models.ManyToManyField(to='ErrorBrowser.errorfilter'),
        ),
    ]
