# Generated by Django 4.1.1 on 2022-10-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErrorBrowser', '0006_errorfilter_stackfilter_delete_columnfilter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errordefinition',
            old_name='filters',
            new_name='errorFilters',
        ),
        migrations.AddField(
            model_name='errordefinition',
            name='stackFilters',
            field=models.ManyToManyField(to='ErrorBrowser.stackfilter'),
        ),
    ]
