# Generated by Django 4.1.1 on 2022-10-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ErrorBrowser', '0007_rename_filters_errordefinition_errorfilters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='errorType',
        ),
        migrations.RemoveField(
            model_name='errortype',
            name='errorCategory',
        ),
        migrations.DeleteModel(
            name='TestMigration',
        ),
        migrations.DeleteModel(
            name='Error',
        ),
        migrations.DeleteModel(
            name='ErrorType',
        ),
    ]
